---

- name: configure_wallpaper | install feh
  package:
    name: feh
    state: installed
  become: yes

- name: configure_wallpaper | drop wallpapers
  copy:
      dest: "{{ configure_wallpaper_directory }}" 
      src: "home/Pictures/wallpapers/{{ configure_wallpaper_resolution }}/"

# - name: configure_wallpaper | install systemd timer

