---

- name: configure_applications | install terminator
  package:
    name: terminator
    state: present
  become: yes

- name: configure_applications | copy configuration
  copy:
    dest: ~/.config
    src: home/.config/terminator
