---

test:
  hosts:
    dev.qcu87z.net:
      ansible_user: ashley
      ansible_host: 127.0.0.1
      configure_bash: true
      configure_wallpaper: false
      configure_vim: true
      configure_applications: true
      ansible_python_interpreter: /usr/bin/python3